In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("Placement.csv")

In [3]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [4]:
Quan = []
Qual = []
for columnName in dataset.columns:
    #print(columnName)
    if(dataset[columnName].dtype=='O'):
        Qual.append(columnName)
    else:
        Quan.append(columnName)

In [36]:
Quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

#Frequency / Relative frequency / Cumulative frequency

In [5]:
dataset['ssc_p'].value_counts

<bound method IndexOpsMixin.value_counts of 0      67.00
1      79.33
2      65.00
3      56.00
4      85.80
       ...
210    80.60
211    58.00
212    67.00
213    74.00
214    62.00
Name: ssc_p, Length: 215, dtype: float64>

In [6]:
dataset['ssc_p'].value_counts().values

array([11, 10,  9,  9,  9,  7,  7,  7,  6,  6,  4,  4,  4,  4,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  2,  2,  2,  2,  2,  2,  2,  2,  2,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1], dtype=int64)

In [7]:
dataset['ssc_p'].value_counts().index

Index([ 62.0,  63.0,  67.0,  52.0,  73.0,  74.0,  65.0,  69.0,  77.0,  58.0,
       ...
        81.7,  64.6,  52.6, 84.86,  75.0,  69.7, 80.92,  83.0,  86.5,  80.6],
      dtype='float64', name='ssc_p', length=103)

In [8]:
dataset['ssc_p'].value_counts().sort_index

<bound method Series.sort_index of ssc_p
62.00    11
63.00    10
67.00     9
52.00     9
73.00     9
         ..
69.70     1
80.92     1
83.00     1
86.50     1
80.60     1
Name: count, Length: 103, dtype: int64>

In [9]:
dataset['ssc_p'].value_counts().sort_values

<bound method Series.sort_values of ssc_p
62.00    11
63.00    10
67.00     9
52.00     9
73.00     9
         ..
69.70     1
80.92     1
83.00     1
86.50     1
80.60     1
Name: count, Length: 103, dtype: int64>

In [43]:
FreqTable=pd.DataFrame(columns=["Unique_values","Frequency","Relative_Frequency","Cumsum"])

In [44]:
FreqTable

Empty DataFrame
Columns: [Unique_values, Frequency, Relative_Frequency, Cumsum]
Index: []

In [45]:
FreqTable["Unique_values"]=dataset["ssc_p"].value_counts().index

In [46]:
FreqTable.head()

   Unique_values Frequency Relative_Frequency Cumsum
0           62.0       NaN                NaN    NaN
1           63.0       NaN                NaN    NaN
2           67.0       NaN                NaN    NaN
3           52.0       NaN                NaN    NaN
4           73.0       NaN                NaN    NaN

In [47]:
FreqTable["Frequency"]=dataset["ssc_p"].value_counts().values

In [48]:
FreqTable.head()

   Unique_values  Frequency Relative_Frequency Cumsum
0           62.0         11                NaN    NaN
1           63.0         10                NaN    NaN
2           67.0          9                NaN    NaN
3           52.0          9                NaN    NaN
4           73.0          9                NaN    NaN

In [49]:
FreqTable["Relative_Frequency"]=FreqTable["Frequency"]/103

In [50]:
FreqTable.head()

   Unique_values  Frequency  Relative_Frequency Cumsum
0           62.0         11            0.106796    NaN
1           63.0         10            0.097087    NaN
2           67.0          9            0.087379    NaN
3           52.0          9            0.087379    NaN
4           73.0          9            0.087379    NaN

In [51]:
FreqTable["Cumsum"]=FreqTable["Relative_Frequency"].cumsum()

In [52]:
FreqTable.head()

   Unique_values  Frequency  Relative_Frequency    Cumsum
0           62.0         11            0.106796  0.106796
1           63.0         10            0.097087  0.203883
2           67.0          9            0.087379  0.291262
3           52.0          9            0.087379  0.378641
4           73.0          9            0.087379  0.466019

# create a function

In [59]:
def FreqTable(columnName,dataset):
    FreqTable=pd.DataFrame(columns=["Unique_values","Frequency","Relative_Frequency","Cumsum"])
    FreqTable["Unique_values"]=dataset[columnName].value_counts().index
    FreqTable["Frequency"]=dataset[columnName].value_counts().values
    FreqTable["Relative_Frequency"]=FreqTable["Frequency"]/103
    FreqTable["Cumsum"]=FreqTable["Relative_Frequency"].cumsum()

    return FreqTable

In [60]:
FreqTable("hsc_p",dataset)

    Unique_values  Frequency  Relative_Frequency    Cumsum
0           63.00         14            0.135922  0.135922
1           62.00         12            0.116505  0.252427
2           67.00          9            0.087379  0.339806
3           60.00          9            0.087379  0.427184
4           64.00          8            0.077670  0.504854
..            ...        ...                 ...       ...
92          83.83          1            0.009709  2.048544
93          70.40          1            0.009709  2.058252
94          90.90          1            0.009709  2.067961
95          89.83          1            0.009709  2.077670
96          42.00          1            0.009709  2.087379

[97 rows x 4 columns]

In [61]:
FreqTable('degree_p',dataset)

    Unique_values  Frequency  Relative_Frequency    Cumsum
0            65.0         20            0.194175  0.194175
1            66.0         13            0.126214  0.320388
2            72.0         12            0.116505  0.436893
3            64.0         11            0.106796  0.543689
4            58.0          9            0.087379  0.631068
..            ...        ...                 ...       ...
84           82.0          1            0.009709  2.048544
85           50.8          1            0.009709  2.058252
86           76.0          1            0.009709  2.067961
87           63.0          1            0.009709  2.077670
88           77.6          1            0.009709  2.087379

[89 rows x 4 columns]

In [62]:
FreqTable('etest_p',dataset)

    Unique_values  Frequency  Relative_Frequency    Cumsum
0           60.00         14            0.135922  0.135922
1           80.00          8            0.077670  0.213592
2           75.00          7            0.067961  0.281553
3           67.00          7            0.067961  0.349515
4           55.00          6            0.058252  0.407767
..            ...        ...                 ...       ...
95          95.46          1            0.009709  2.048544
96          93.91          1            0.009709  2.058252
97          56.39          1            0.009709  2.067961
98          57.50          1            0.009709  2.077670
99          91.00          1            0.009709  2.087379

[100 rows x 4 columns]

In [63]:
FreqTable('mba_p',dataset)

     Unique_values  Frequency  Relative_Frequency    Cumsum
0            56.70          3            0.029126  0.029126
1            66.94          2            0.019417  0.048544
2            59.47          2            0.019417  0.067961
3            60.44          2            0.019417  0.087379
4            68.07          2            0.019417  0.106796
..             ...        ...                 ...       ...
200          67.00          1            0.009709  2.048544
201          64.27          1            0.009709  2.058252
202          57.65          1            0.009709  2.067961
203          59.42          1            0.009709  2.077670
204          60.22          1            0.009709  2.087379

[205 rows x 4 columns]

In [64]:
FreqTable('salary',dataset)

    Unique_values  Frequency  Relative_Frequency    Cumsum
0        300000.0         22            0.213592  0.213592
1        250000.0         18            0.174757  0.388350
2        240000.0         15            0.145631  0.533981
3        260000.0          7            0.067961  0.601942
4        360000.0          6            0.058252  0.660194
5        200000.0          6            0.058252  0.718447
6        265000.0          6            0.058252  0.776699
7        220000.0          5            0.048544  0.825243
8        275000.0          5            0.048544  0.873786
9        210000.0          4            0.038835  0.912621
10       400000.0          4            0.038835  0.951456
11       270000.0          4            0.038835  0.990291
12       216000.0          3            0.029126  1.019417
13       350000.0          3            0.029126  1.048544
14       500000.0          3            0.029126  1.077670
15       252000.0          2            0.019417  1.097087
16       236000.0          2            0.019417  1.116505
17       230000.0          2            0.019417  1.135922
18       280000.0          2            0.019417  1.155340
19       218000.0          2            0.019417  1.174757
20       204000.0          2            0.019417  1.194175
21       276000.0          2            0.019417  1.213592
22       255000.0          1            0.009709  1.223301
23       285000.0          1            0.009709  1.233010
24       340000.0          1            0.009709  1.242718
25       690000.0          1            0.009709  1.252427
26       233000.0          1            0.009709  1.262136
27       290000.0          1            0.009709  1.271845
28       650000.0          1            0.009709  1.281553
29       264000.0          1            0.009709  1.291262
30       225000.0          1            0.009709  1.300971
31       940000.0          1            0.009709  1.310680
32       393000.0          1            0.009709  1.320388
33       380000.0          1            0.009709  1.330097
34       420000.0          1            0.009709  1.339806
35       425000.0          1            0.009709  1.349515
36       336000.0          1            0.009709  1.359223
37       231000.0          1            0.009709  1.368932
38       268000.0          1            0.009709  1.378641
39       450000.0          1            0.009709  1.388350
40       287000.0          1            0.009709  1.398058
41       411000.0          1            0.009709  1.407767
42       320000.0          1            0.009709  1.417476
43       278000.0          1            0.009709  1.427184
44       295000.0          1            0.009709  1.436893