In [ ]:
#import the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("insurance_pre.csv")

In [3]:
data.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [4]:
data.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
charges     0
dtype: int64

In [5]:
data=pd.get_dummies(data,drop_first=True)

In [6]:
data=data.astype(int)

In [7]:
data.head()

   age  bmi  children  charges  sex_male  smoker_yes
0   19   27         0    16884         0           1
1   18   33         1     1725         1           0
2   28   33         3     4449         1           0
3   33   22         0    21984         1           0
4   32   28         0     3866         1           0

In [ ]:
#split independent and dependent

In [8]:
data.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [9]:
independent=data[['age','bmi','children','sex_male','smoker_yes']]

In [10]:
dependent=data[['charges']]

In [11]:
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [12]:
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [ ]:
#training and test data split

In [ ]:
#from sklearn.model_selection import train_test_split

In [ ]:
#x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [ ]:
#x_train,x_test,y_train,y_test

In [ ]:
#standardscalar

In [ ]:
#from sklearn.preprocessing import StandardScaler
#sc = StandardScaler()
#x_train = sc.fit_transform(x_train)
#x_test = sc.transform(x_test)

In [ ]:
#GridSearchCV

In [13]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','poly','sigmoid','linear'],
'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3,n_jobs=-1)

In [ ]:
# fitting the model for grid search

In [ ]:
grid.fit(independent,dependent)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

In [ ]:
# print best parameter after tuning
#print(grid.best_params_)

In [ ]:
re=grid.cv_results_
#print(re)#grid_predictions=grid.predict(x_test)
#print classification report
#from sklearn.metrics import r2_score
#r_score=r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_))

In [ ]:
table=pd.DataFrame.from_dict(re)

In [ ]:
table

In [ ]:
#input getting from user for future prediction

In [ ]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

In [ ]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))