In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("PrePlacementdata.csv")

In [3]:
dataset.head()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,1.0,67.00,91.00,58.00,55.0,58.80,270000.0,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,2.0,79.33,78.33,77.48,86.5,66.28,200000.0,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,3.0,65.00,68.00,64.00,75.0,57.80,250000.0,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,4.0,56.00,52.00,52.00,66.0,59.43,0.0,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,5.0,85.80,73.60,73.30,96.8,55.50,425000.0,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed

In [4]:
dataset.isnull().sum()

sl_no             0
ssc_p             0
hsc_p             0
degree_p          0
etest_p           0
mba_p             0
salary            0
gender            0
ssc_b             0
hsc_b             0
hsc_s             0
degree_t          0
workex            0
specialisation    0
status            0
dtype: int64

In [5]:
dataset["gender"]=='M'

0       True
1       True
2       True
3       True
4       True
       ...
210     True
211     True
212     True
213    False
214     True
Name: gender, Length: 215, dtype: bool

In [6]:
dataset[dataset["gender"]=='M']

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,1.0,67.00,91.00,58.00,55.0,58.80,270000.0,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,2.0,79.33,78.33,77.48,86.5,66.28,200000.0,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,3.0,65.00,68.00,64.00,75.0,57.80,250000.0,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,4.0,56.00,52.00,52.00,66.0,59.43,0.0,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,5.0,85.80,73.60,73.30,96.8,55.50,425000.0,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,210.0,62.00,72.00,65.00,67.0,56.49,216000.0,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
210,211.0,80.60,82.00,77.60,91.0,74.49,400000.0,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,212.0,58.00,60.00,72.00,74.0,53.62,275000.0,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,213.0,67.00,67.00,73.00,59.0,69.72,295000.0,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
214,215.0,62.00,58.00,53.00,89.0,60.22,0.0,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [7]:
dataset[dataset["gender"]=='F']

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
6,7.0,46.00,49.2,79.0,74.28,53.29,0.0,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Not Placed
12,13.0,47.00,55.0,65.0,62.00,65.04,0.0,F,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed
13,14.0,77.00,87.0,59.0,68.00,68.63,218000.0,F,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
15,16.0,65.00,75.0,69.0,72.00,64.66,200000.0,F,Central,Central,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
17,18.0,55.00,67.0,64.0,60.00,67.28,0.0,F,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Not Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,198.0,83.96,53.0,91.0,59.32,69.71,260000.0,F,Others,Others,Science,Sci&Tech,No,Mkt&HR,Placed
198,199.0,67.00,70.0,65.0,88.00,71.96,0.0,F,Central,Central,Commerce,Others,No,Mkt&HR,Not Placed
204,205.0,74.00,73.0,73.0,80.00,67.69,210000.0,F,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
208,209.0,43.00,60.0,65.0,92.66,62.92,0.0,F,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed
213,214.0,74.00,66.0,58.0,70.00,60.23,204000.0,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed

In [8]:
dataset[dataset["gender"]=='M']["salary"]

0      270000.0
1      200000.0
2      250000.0
3           0.0
4      425000.0
         ...
209    216000.0
210    400000.0
211    275000.0
212    295000.0
214         0.0
Name: salary, Length: 139, dtype: float64

# independent sample - unpaired T-Test

Different Group(Male,Female) but same conditions (salary)

In [9]:
from scipy.stats import ttest_ind
dataset=dataset.dropna()
male=dataset[dataset["gender"]=="M"]["salary"]
female=dataset[dataset["gender"]=="F"]["salary"]
print (male)

0      270000.0
1      200000.0
2      250000.0
3           0.0
4      425000.0
         ...
209    216000.0
210    400000.0
211    275000.0
212    295000.0
214         0.0
Name: salary, Length: 139, dtype: float64

In [10]:
ttest_ind(male,female)

TtestResult(statistic=2.1103433958668765, pvalue=0.03599560646745178, df=213.0)

# Dependent sample -paired T-Test

Same Group(Male) but different conditions (ssc_p and hsc_p)

In [11]:
from scipy.stats import ttest_rel
male1=dataset[dataset["gender"]=="M"]["ssc_p"]
male2=dataset[dataset["gender"]=="M"]["hsc_p"]
ttest_rel(male1,male2)

TtestResult(statistic=0.6852881050898076, pvalue=0.49431164600731514, df=138)

# Hypothesis Testing

Statement : Test whether ssc_p of male and hsc_p of male is same?

Null hypothesis : There is no similarity between 10th pass mark of male and 12th pass mark of male.

In [12]:
from scipy.stats import ttest_rel
male1=dataset[dataset["gender"]=="M"]["ssc_p"]
male2=dataset[dataset["gender"]=="M"]["hsc_p"]
ttest_rel(male1,male2)

TtestResult(statistic=0.6852881050898076, pvalue=0.49431164600731514, df=138)

In [13]:
# Reject null hypothesis when the p value is <0.05 .Here p value is > 0.05 .so that, reject alternate hypothesis and accept null hypothesis.

# ANOVA(Analysis of variance)

In [14]:
import scipy.stats as stats
stats.f_oneway(dataset["ssc_p"],dataset["hsc_p"],dataset["degree_p"])

F_onewayResult(statistic=0.6719700864663097, pvalue=0.5110602818995302)

Reject null hypothesis when the p value is <0.05 .Here p value is > 0.05 .so that, reject alternate hypothesis and accept null hypothesis.