In [ ]:
#import the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("insurance_pre.csv")

In [3]:
data.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [4]:
data.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
charges     0
dtype: int64

In [5]:
data=pd.get_dummies(data,drop_first=True)

In [6]:
data=data.astype(int)

In [7]:
data.head()

   age  bmi  children  charges  sex_male  smoker_yes
0   19   27         0    16884         0           1
1   18   33         1     1725         1           0
2   28   33         3     4449         1           0
3   33   22         0    21984         1           0
4   32   28         0     3866         1           0

In [8]:
#split independent and dependent

In [9]:
data.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [10]:
independent=data[['age','bmi','children','sex_male','smoker_yes']]

In [11]:
dependent=data[['charges']]

In [12]:
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [13]:
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [14]:
#training and test data split

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [17]:
x_train,x_test,y_train,y_test

(      age  bmi  children  sex_male  smoker_yes
 1163   18   28         0         0           0
 196    39   32         0         0           0
 438    52   46         5         0           0
 183    44   26         0         0           0
 1298   33   27         2         1           0
 ...   ...  ...       ...       ...         ...
 763    27   26         0         1           0
 835    42   35         2         1           0
 1216   40   25         0         1           0
 559    19   35         0         1           0
 684    33   18         1         0           0

 [936 rows x 5 columns],
       age  bmi  children  sex_male  smoker_yes
 578    52   30         1         1           0
 610    47   29         1         0           0
 569    48   40         2         1           1
 1034   61   38         0         1           0
 198    51   18         0         0           0
 ...   ...  ...       ...       ...         ...
 1261   28   37         1         1           0
 494    21   25         4         1           1
 97     55   38         0         1           0
 418    64   39         1         1           0
 920    62   25         0         0           0

 [402 rows x 5 columns],
       charges
 1163     2200
 196      5649
 438     12592
 183      7419
 1298     5261
 ...       ...
 763      3070
 835      7160
 1216     5415
 559      1646
 684      4766

 [936 rows x 1 columns],
       charges
 578      9724
 610      8547
 569     45702
 1034    12950
 198      9644
 ...       ...
 1261     3277
 494     17942
 97      10226
 418     14418
 920     13451

 [402 rows x 1 columns])

In [18]:
#standardscalar

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [20]:
#GridSearchCV

In [21]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','poly','sigmoid','linear'],
'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3,n_jobs=-1)

In [22]:
# fitting the model for grid search

In [23]:
grid.fit(x_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [24]:
# print best parameter after tuning
#print(grid.best_params_)

In [25]:
re=grid.cv_results_
#print(re)#grid_predictions=grid.predict(x_test)
#print classification report
#from sklearn.metrics import r2_score
#r_score=r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}:

In [26]:
table=pd.DataFrame.from_dict(re)

In [27]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.087882,0.017321,0.036751,3.913186e-03,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.004062,0.013335,-0.103476,-0.095366,-0.101569,-0.056603,0.053466,35
1,0.055126,0.010839,0.008789,1.597667e-03,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.055924,0.069452,-0.045421,-0.025445,-0.049485,0.001005,0.051196,32
2,0.082289,0.011741,0.012783,1.598048e-03,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.050024,0.076009,-0.046805,-0.041071,-0.046774,-0.001724,0.053536,34
3,0.053528,0.009979,0.009587,1.956764e-03,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.377724,0.479574,0.317907,0.338157,0.324423,0.367557,0.059735,25
4,0.071903,0.017321,0.031958,9.956652e-07,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.004135,0.013210,-0.103428,-0.095408,-0.101569,-0.056612,0.053448,36
5,0.063918,0.008379,0.009584,1.954200e-03,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.054577,0.071249,-0.046156,-0.024590,-0.049471,0.001122,0.051442,31
6,0.074301,0.007410,0.012783,1.598239e-03,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.049754,0.076446,-0.046990,-0.040903,-0.046771,-0.001693,0.053617,33
7,0.055925,0.012633,0.008788,1.598859e-03,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.377724,0.479574,0.317907,0.338157,0.324423,0.367557,0.059735,25
8,0.070306,0.010896,0.035153,8.530540e-03,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.300124,0.339544,0.174257,0.217017,0.183337,0.242856,0.065642,29
9,0.067908,0.011851,0.009588,1.957406e-03,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.537814,0.574688,0.470001,0.532987,0.425034,0.508105,0.053456,22
10,0.075099,0.008896,0.014381,3.195763e-03,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.482712,0.560842,0.433137,0.449720,0.431324,0.471547,0.048307,23
11,0.072704,0.017394,0.008788,1.599264e-03,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.584840,0.656088,0.553185,0.577115,0.547448,0.583735,0.038807,19
12,0.063915,0.009109,0.032756,1.597929e-03,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.300606,0.338790,0.174699,0.216705,0.183330,0.242826,0.065439,30
13,0.055925,0.004376,0.010387,1.956900e-03,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.534189,0.579262,0.467718,0.534956,0.425072,0.508240,0.054754,21
14,0.088680,0.019142,0.011984,1.059824e-06,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.481175,0.561849,0.429295,0.451834,0.431336,0.471098,0.049065,24
15,0.070306,0.006492,0.010387,3.195727e-03,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.584840,0.656088,0.553185,0.577115,0.547448,0.583735,0.038807,19
16,0.086284,0.011185,0.038349,8.968048e-03,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.731988,0.743653,0.686787,0.715193,0.644532,0.704430,0.035532,12
17,0.091877,0.011299,0.009587,1.957445e-03,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.830806,0.806043,0.799112,0.802509,0.739945,0.795683,0.030020,7
18,0.081491,0.011186,0.013581,3.195548e-03,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.323851,0.371445,0.287282,0.286805,0.351347,0.324146,0.033854,27
19,0.083888,0.012117,0.010386,3.196347e-03,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.604973,0.589001,0.623195,0.538195,0.617342,0.594541,0.030513,17
20,0.089480,0.008605,0.041545,8.604407e-03,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.732239,0.743319,0.687028,0.715059,0.644529,0.704435,0.035467,11
21,0.090279,0.005420,0.009588,1.957328e-03,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.829390,0.805648,0.798663,0.802669,0.739952,0.795264,0.029659,8
22,0.083088,0.009915,0.015180,3.914111e-03,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.328341,0.386884,0.216176,0.287478,0.351327,0.314041,0.058624,28
23,0.072703,0.003914,0.011185,1.598668e-03,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.604973,0.589001,0.623195,0.538195,0.617342,0.594541,0.030513,17
24,0.099866,0.015369,0.032757,1.597905e-03,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.816190,0.779806,0.791733,0.791076,0.732585,0.782278,0.027540,10
25,0.140612,0.023072,0.009587,1.957347e-03,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.847468,0.808587,0.813767,0.803786,0.755123,0.805746,0.029596,3
26,0.098269,0.010294,0.012783,1.598096e-03,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.445302,-0.511012,-0.493784,-0.461297,-0.099723,-0.402223,0.153017,37
27,0.106258,0.013030,0.009588,1.957639e-03,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.605615,0.583248,0.697406,0.532387,0.681584,0.620048,0.061673,15
28,0.095872,0.006685,0.034354,1.956686e-03,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.816457,0.779685,0.791839,0.790950,0.732583,0.782303,0.027609,9
29,0.165379,0.038283,0.012784,7.746779e-03,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.847539,0.808183,0.813734,0.803711,0.755123,0.805658,0.029608,4
30,0.099866,0.011298,0.017577,9.317455e-03,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.616220,-0.532822,-0.478194,-0.542484,-0.102534,-0.454451,0.181367,38
31,0.099067,0.006392,0.009588,1.957231e-03,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.605615,0.583248,0.697406,0.532387,0.681584,0.620048,0.061673,15
32,0.100665,0.011958,0.035154,2.989209e-03,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.829220,0.791264,0.810701,0.809750,0.742128,0.796613,0.029771,6
33,0.205967,0.062634,0.010386,1.957464e-03,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.850124,0.806758,0.814590,0.804422,0.757864,0.806752,0.029455,1
34,0.088962,0.007866,0.013835,3.574011e-03,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-1.754076,-2.044957,-1.699509,-1.914567,-1.035870,-1.689796,0.348857,40
35,0.128431,0.012039,0.008788,1.598167e-03,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.657721,0.583243,0.697893,0.529476,0.655869,0.624840,0.060341,13
36,0.113448,0.017246,0.031958,6.641573e-07,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.829352,0.791147,0.810772,0.809730,0.742127,0.796625,0.029809,5
37,0.203727,0.044910,0.008788,1.598097e-03,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.850157,0.806802,0.814553,0.804154,0.757866,0.806706,0.029467,2
38,0.103062,0.020587,0.015979,6.188045e-03,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.682090,-1.830750,-1.676185,-1.941103,-1.036223,-1.633270,0.314468,39
39,0.105459,0.006965,0.008789,1.598001e-03,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.657721,0.583243,0.697893,0.529476,0.655869,0.624840,0.060341,13

In [28]:
#input getting from user for future prediction

In [31]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:40
BMI:51
Children:3
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [32]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[7389636.85064014]