## Life cycle of Machine learning Project
    1.Understanding the Problem Statement (Data set)
    2.Data Collection
    3.Data Checks to perform
    4.Exploratory data analysis
    5.Data Pre-Processing
    6.Model Training
    7.Choose and save best model

## 1) Problem statement
 This project aims to study how climate change affects agriculture by analyzing the connection between climate factors such as temperature, rainfall, and CO2 levels, and agricultural outcomes like crop yields and soil quality.
## 2) Data Collection
Dataset Source - https://www.kaggle.com/datasets/waqi786/climate-change-impact-on-agriculture
                                                The data consists of 15 columns and 10000 rows.

## 2.1 Import Data and Required Packages
Importing Pandas, Numpy, Matplotlib, Seaborn and Warings Library.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

## Import the CSV Data as Pandas DataFrame

In [2]:
dataset=pd.read_csv("data/climate_change_impact_on_agriculture_2024.csv")

In [3]:
dataset

,Year,Country,Region,Crop_Type,Average_Temperature_C,Total_Precipitation_mm,CO2_Emissions_MT,Crop_Yield_MT_per_HA,Extreme_Weather_Events,Irrigation_Access_%,Pesticide_Use_KG_per_HA,Fertilizer_Use_KG_per_HA,Soil_Health_Index,Adaptation_Strategies,Economic_Impact_Million_USD
0,2001,India,West Bengal,Corn,1.55,447.06,15.22,1.737,8,14.54,10.08,14.78,83.25,Water Management,808.13
1,2024,China,North,Corn,3.23,2913.57,29.82,1.737,8,11.05,33.06,23.25,54.02,Crop Rotation,616.22
2,2001,France,Ile-de-France,Wheat,21.11,1301.74,25.75,1.719,5,84.42,27.41,65.53,67.78,Water Management,796.96
3,2001,Canada,Prairies,Coffee,27.85,1154.36,13.91,3.890,5,94.06,14.38,87.58,91.39,No Adaptation,790.32
4,1998,India,Tamil Nadu,Sugarcane,2.19,1627.48,11.81,1.080,9,95.75,44.35,88.08,49.61,Crop Rotation,401.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022,France,Nouvelle-Aquitaine,Cotton,30.48,685.93,17.64,3.033,9,27.56,41.96,10.95,43.41,No Adaptation,1483.06
9996,1999,Australia,Queensland,Soybeans,9.53,2560.38,10.68,2.560,4,77.02,5.45,82.32,59.39,No Adaptation,829.61
9997,2000,Argentina,Patagonia,Coffee,31.92,357.76,26.01,1.161,10,78.53,11.94,26.00,41.46,Water Management,155.99
9998,1996,Brazil,Southeast,Soybeans,13.95,1549.52,17.31,3.348,2,42.65,44.71,25.07,75.10,Crop Rotation,1613.90
9999,2015,China,South,Corn,11.78,1676.25,5.34,3.710,5,46.41,48.28,98.27,59.38,Water Management,453.14

## copy the dataset in another file

In [4]:
df=dataset

In [5]:
df.head(3)

,Year,Country,Region,Crop_Type,Average_Temperature_C,Total_Precipitation_mm,CO2_Emissions_MT,Crop_Yield_MT_per_HA,Extreme_Weather_Events,Irrigation_Access_%,Pesticide_Use_KG_per_HA,Fertilizer_Use_KG_per_HA,Soil_Health_Index,Adaptation_Strategies,Economic_Impact_Million_USD
0,2001,India,West Bengal,Corn,1.55,447.06,15.22,1.737,8,14.54,10.08,14.78,83.25,Water Management,808.13
1,2024,China,North,Corn,3.23,2913.57,29.82,1.737,8,11.05,33.06,23.25,54.02,Crop Rotation,616.22
2,2001,France,Ile-de-France,Wheat,21.11,1301.74,25.75,1.719,5,84.42,27.41,65.53,67.78,Water Management,796.96

In [6]:
df.shape

(10000, 15)

10000- rows and 15 columns

### 2.2 Dataset information

- year : The year in which the data was collected.This helps in analyzing trends over time, such as how climate factors and crop yields have changed across years.
- country : The country where the agricultural data was collected.Knowing the country helps in understanding region-specific climate impacts and agricultural practices.
- Region : The specific region within the country where the data is collected. This gives a more granular view, as climate conditions and agricultural outputs can vary significantly between regions within the same country.
- Crop_Type: The type of crop being grown and measured.Different crops respond differently to climate variables, so this column helps in studying crop-specific climate impacts.
- Average_Temperature_C: The average temperature (in degrees Celsius) during the growing season or the specified period. Temperature is a crucial climate variable affecting crop growth. Higher or lower temperatures than optimal can affect crop yield.
- Total_Precipitation_mm : The total precipitation (rainfall, snow, etc.) in millimeters during the growing season or the specified period.  Precipitation is vital for crop health. Too much or too little rain can impact crop yields, leading to droughts or floods.
- Co2_Emissions_MT: The total carbon dioxide (CO2) emissions in metric tons (MT) associated with the region or agricultural activities during the specified time. CO2 emissions contribute to climate change, which indirectly affects agricultural productivity by altering temperatures, weather patterns, and soil health.
- crop_yield_MT_per_HA : The crop yield measured in metric tons (MT) per hectare (HA) of land. This is the key measure of agricultural productivity, showing how much crop is harvested per hectare. It's influenced by climate conditions, soil health, and farming practices.
- Extreme_weather_Events : The number of extreme weather events (like storms, droughts, floods) that occurred in the region during the specified period.Extreme weather events can drastically affect agricultural productivity by damaging crops or reducing soil fertility.
- Irrigation_Access_% : The percentage of farmland that has access to irrigation systems in the region. Irrigation access helps ensure crops receive enough water even in regions with low rainfall, thus stabilizing or increasing crop yields.
- Pesticide_Use_KG_per_HA : The amount of pesticide used per hectare of land, measured in kilograms (KG). Pesticides are used to protect crops from pests and diseases, but excessive use can have negative effects on the environment and soil health.
- Fertilizer_Use_KG_per_HA : The amount of fertilizer used per hectare of land, measured in kilograms (KG). Fertilizers are used to enhance soil fertility and improve crop yields. However, overuse can lead to soil degradation and environmental pollution.
- Soil_Health_Index :An index value representing the health of the soil, considering factors like organic matter, nutrient content, and moisture retention. Soil health is critical for long-term agricultural sustainability. Poor soil health can lead to lower crop yields and the need for more inputs like fertilizers.
- Adaptation_Strategies :  The strategies employed by farmers or regions to adapt to climate change, such as crop rotation, water management, or no adaptation.Adaptation strategies are important for mitigating the effects of climate change on agriculture and ensuring sustainable productivity.
- Economic_Impact_Million_USD : The economic impact of climate factors and agriculture, measured in millions of US dollars.This represents the financial outcomes of agricultural activities, factoring in production costs, losses due to climate change, and revenue from crop sales.

Summary:
This dataset contains variables related to climate factors, agricultural practices, crop productivity, soil health, and the economic impact of farming in different regions and years. It helps in analyzing how changes in temperature, rainfall, CO2 levels, and extreme weather events affect crop yields and economic outcomes, as well as the adaptation strategies used to mitigate these effects.

### 3. Data Checks to perform

- Check Missing values
- Check Duplicates
- Check data type
- Check the number of unique values of each column
- Check statistics of data set
- Check various categories present in the different categorical column

### 3.1 Check Missing values

In [7]:
df.isnull().sum()

Year                           0
Country                        0
Region                         0
Crop_Type                      0
Average_Temperature_C          0
Total_Precipitation_mm         0
CO2_Emissions_MT               0
Crop_Yield_MT_per_HA           0
Extreme_Weather_Events         0
Irrigation_Access_%            0
Pesticide_Use_KG_per_HA        0
Fertilizer_Use_KG_per_HA       0
Soil_Health_Index              0
Adaptation_Strategies          0
Economic_Impact_Million_USD    0
dtype: int64

#### There are no missing values in the data set

### 3.2 Check Duplicates

In [8]:
df.duplicated().sum()

0

#### There are no duplicates  values in the data set

### 3.3 Check data types

In [9]:
# Check Null and Dtypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         10000 non-null  int64
 1   Country                      10000 non-null  object
 2   Region                       10000 non-null  object
 3   Crop_Type                    10000 non-null  object
 4   Average_Temperature_C        10000 non-null  float64
 5   Total_Precipitation_mm       10000 non-null  float64
 6   CO2_Emissions_MT             10000 non-null  float64
 7   Crop_Yield_MT_per_HA         10000 non-null  float64
 8   Extreme_Weather_Events       10000 non-null  int64
 9   Irrigation_Access_%          10000 non-null  float64
 10  Pesticide_Use_KG_per_HA      10000 non-null  float64
 11  Fertilizer_Use_KG_per_HA     10000 non-null  float64
 12  Soil_Health_Index            10000 non-null  float64
 13  Adaptation_Strategies        10000 non-null  object
 14  Economic_Impact_Million_USD  10000 non-null  float64
dtypes: float64(9), int64(2), object(4)
memory usage: 1.1+ MB

### 3.4 Checking the number of unique values of each column

In [10]:
df.nunique()

Year                             35
Country                          10
Region                           34
Crop_Type                        10
Average_Temperature_C          3677
Total_Precipitation_mm         9784
CO2_Emissions_MT               2852
Crop_Yield_MT_per_HA            850
Extreme_Weather_Events           11
Irrigation_Access_%            6003
Pesticide_Use_KG_per_HA        4343
Fertilizer_Use_KG_per_HA       6314
Soil_Health_Index              5318
Adaptation_Strategies             5
Economic_Impact_Million_USD    9631
dtype: int64

### 3.5 Check statistics of data set

In [11]:
df.describe()

,Year,Average_Temperature_C,Total_Precipitation_mm,CO2_Emissions_MT,Crop_Yield_MT_per_HA,Extreme_Weather_Events,Irrigation_Access_%,Pesticide_Use_KG_per_HA,Fertilizer_Use_KG_per_HA,Soil_Health_Index,Economic_Impact_Million_USD
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2007.088700,15.241299,1611.663834,15.246608,2.240017,4.980900,55.248332,24.955735,49.973708,64.901278,674.269658
std,10.084245,11.466955,805.016815,8.589423,0.998342,3.165808,25.988305,14.490962,28.711027,20.195882,414.591431
min,1990.000000,-4.990000,200.150000,0.500000,0.450000,0.000000,10.010000,0.000000,0.010000,30.000000,47.840000
25%,1999.000000,5.430000,925.697500,7.760000,1.449000,2.000000,32.677500,12.527500,25.390000,47.235000,350.545000
50%,2007.000000,15.175000,1611.160000,15.200000,2.170000,5.000000,55.175000,24.930000,49.635000,64.650000,583.920000
75%,2016.000000,25.340000,2306.997500,22.820000,2.930000,8.000000,77.582500,37.470000,74.825000,82.472500,917.505000
max,2024.000000,35.000000,2999.670000,30.000000,5.000000,10.000000,99.990000,49.990000,99.990000,100.000000,2346.470000

#### Insight
- From above description of numerical data, all means are not close to each other 
- All standard deviations are also not close 
- While there is a minimum score  0 for Extreme_Weather_Events,Pesticide_Use_KG_per_HA, for Total_Precipitation_mm minimum is much higher = 200 and for Soil_Health_Index higher = 30

### 4.Exploratory Data Analysis (Descriptive Data analysis + Inferential data ANalysis)

##### 4.1. Univariate Analysis
##### 4.2. Bivariate Analysis
##### 4.3. Mutlivariate Analysis

##### 4.1. Univariate Analysis(continuous and Discreate)
            4.1.1. if continuous:
                4.1.1.1. Measure of central tendency (Mean,Median,Mode)
                4.1.1.2. Measure of location of the data (Frequency,cumulative frequency,Percentile,InterQuantile percentile,Range)
                4.1.1.3. Histogram and skewness
                4.1.1.4. Measure of Spread (Variance,Standard deviation,z-score)

            4.1.2. if Discreate
                4.1.2.1. Frequency Analysis (Bar chart,pie chart,Graps)

In [12]:
df.head()

,Year,Country,Region,Crop_Type,Average_Temperature_C,Total_Precipitation_mm,CO2_Emissions_MT,Crop_Yield_MT_per_HA,Extreme_Weather_Events,Irrigation_Access_%,Pesticide_Use_KG_per_HA,Fertilizer_Use_KG_per_HA,Soil_Health_Index,Adaptation_Strategies,Economic_Impact_Million_USD
0,2001,India,West Bengal,Corn,1.55,447.06,15.22,1.737,8,14.54,10.08,14.78,83.25,Water Management,808.13
1,2024,China,North,Corn,3.23,2913.57,29.82,1.737,8,11.05,33.06,23.25,54.02,Crop Rotation,616.22
2,2001,France,Ile-de-France,Wheat,21.11,1301.74,25.75,1.719,5,84.42,27.41,65.53,67.78,Water Management,796.96
3,2001,Canada,Prairies,Coffee,27.85,1154.36,13.91,3.890,5,94.06,14.38,87.58,91.39,No Adaptation,790.32
4,1998,India,Tamil Nadu,Sugarcane,2.19,1627.48,11.81,1.080,9,95.75,44.35,88.08,49.61,Crop Rotation,401.72

# Separate Quan and Qual

In [13]:
df.columns

Index(['Year', 'Country', 'Region', 'Crop_Type', 'Average_Temperature_C',
       'Total_Precipitation_mm', 'CO2_Emissions_MT', 'Crop_Yield_MT_per_HA',
       'Extreme_Weather_Events', 'Irrigation_Access_%',
       'Pesticide_Use_KG_per_HA', 'Fertilizer_Use_KG_per_HA',
       'Soil_Health_Index', 'Adaptation_Strategies',
       'Economic_Impact_Million_USD'],
      dtype='object')

In [14]:
def QuanQual(df):
    Quan = [feature for feature in df.columns if df[feature].dtype != 'O']
    Qual = [feature for feature in df.columns if df[feature].dtype == 'O']
    return Quan,Qual

In [15]:
Quan,Qual= QuanQual(df)

In [16]:
Quan

['Year',
 'Average_Temperature_C',
 'Total_Precipitation_mm',
 'CO2_Emissions_MT',
 'Crop_Yield_MT_per_HA',
 'Extreme_Weather_Events',
 'Irrigation_Access_%',
 'Pesticide_Use_KG_per_HA',
 'Fertilizer_Use_KG_per_HA',
 'Soil_Health_Index',
 'Economic_Impact_Million_USD']

In [17]:
Qual

['Country', 'Region', 'Crop_Type', 'Adaptation_Strategies']

### 4.1.1.1 Measure of central tendency (1.Mean, 2.Median,3.Mode)
### 4.1.1,2. Measure of location of the data (3.Percentile and 4.InterQuantile percentile)
### 4.1.1.3. Histogram and skewness,kurtosis
### 4.1.1.4. Measure of Spread (Variance,Standard deviation)

In [18]:
from UnivariateAnalysis import Univariate
import numpy as np
result = Univariate.descriptive(df,Quan)
result

,Year,Average_Temperature_C,Total_Precipitation_mm,CO2_Emissions_MT,Crop_Yield_MT_per_HA,Extreme_Weather_Events,Irrigation_Access_%,Pesticide_Use_KG_per_HA,Fertilizer_Use_KG_per_HA,Soil_Health_Index,Economic_Impact_Million_USD
Mean,2007.0887,15.241299,1611.663834,15.246608,2.240017,4.9809,55.248332,24.955735,49.973708,64.901278,674.269658
Median,2007.0,15.175,1611.16,15.2,2.17,5.0,55.175,24.93,49.635,64.65,583.92
Mode,1999,3.41,1377.47,25.23,1.53,1,79.29,0.72,6.07,79.38,616.6
Q1:25%,1999.0,5.43,925.6975,7.76,1.449,2.0,32.6775,12.5275,25.39,47.235,350.545
Q2:50%,2007.0,15.175,1611.16,15.2,2.17,5.0,55.175,24.93,49.635,64.65,583.92
Q3:75%,2016.0,25.34,2306.9975,22.82,2.93,8.0,77.5825,37.47,74.825,82.4725,917.505
99%,2024.0,34.62,2975.9511,29.73,4.63,10.0,98.9302,49.46,98.9301,99.3502,1897.497
Q4:100%,2024.0,35.0,2999.67,30.0,5.0,10.0,99.99,49.99,99.99,100.0,2346.47
IQR,17.0,19.91,1381.3,15.06,1.481,6.0,44.905,24.9425,49.435,35.2375,566.96
1.5_Rule,25.5,29.865,2071.95,22.59,2.2215,9.0,67.3575,37.41375,74.1525,52.85625,850.44
Lesser_outlier,1973.5,-24.435,-1146.2525,-14.83,-0.7725,-7.0,-34.68,-24.88625,-48.7625,-5.62125,-499.895
Greater_outlier,2041.5,55.205,4378.9475,45.41,5.1515,17.0,144.94,74.88375,148.9775,135.32875,1767.945
Min,1990,-4.99,200.15,0.5,0.45,0,10.01,0.0,0.01,30.0,47.84
Max,2024,35.0,2999.67,30.0,5.0,10,99.99,49.99,99.99,100.0,2346.47
skewness,-0.006793,-0.011513,-0.006014,0.009935,0.357311,0.011543,-0.008659,-0.001524,0.013391,0.011196,0.961771
kurtosis,-1.20695,-1.190673,-1.187626,-1.209761,-0.56576,-1.223471,-1.199248,-1.206221,-1.193914,-1.195908,0.587771
Var,101.692002,131.491048,648052.072133,73.778186,0.996686,10.022337,675.391983,209.987987,824.323068,407.873663,171886.054984
std,10.084245,11.466955,805.016815,8.589423,0.998342,3.165808,25.988305,14.490962,28.711027,20.195882,414.591431

### 4.1.1.2. Measure of location of the data (1.Frequency,2.Cumulative Frequency)
### "Unique_values","Frequency","Relative_Frequency","Cumsum"

In [19]:
from UnivariateAnalysis import Univariate
#import pandas as pd
#import numpy as np
result = Univariate.FreqTable("Average_Temperature_C",df)
result

      Unique_values  Frequency  Relative_Frequency     Cumsum
0              3.41          9            0.087379   0.087379
1             33.19          9            0.087379   0.174757
2             20.35          9            0.087379   0.262136
3             18.13          8            0.077670   0.339806
4              0.15          8            0.077670   0.417476
...             ...        ...                 ...        ...
3672          12.63          1            0.009709  97.048544
3673          17.48          1            0.009709  97.058252
3674           3.03          1            0.009709  97.067961
3675           1.28          1            0.009709  97.077670
3676           9.53          1            0.009709  97.087379

[3677 rows x 4 columns]

In [20]:
result = Univariate.FreqTable("Total_Precipitation_mm",df)
result

      Unique_values  Frequency  Relative_Frequency     Cumsum
0           1377.47          3            0.029126   0.029126
1           2624.98          2            0.019417   0.048544
2           2642.21          2            0.019417   0.067961
3           2855.34          2            0.019417   0.087379
4            679.97          2            0.019417   0.106796
...             ...        ...                 ...        ...
9779        2373.23          1            0.009709  97.048544
9780        1841.78          1            0.009709  97.058252
9781        2388.71          1            0.009709  97.067961
9782        1061.11          1            0.009709  97.077670
9783        1676.25          1            0.009709  97.087379

[9784 rows x 4 columns]

In [21]:
result = Univariate.FreqTable("CO2_Emissions_MT",df)
result

      Unique_values  Frequency  Relative_Frequency     Cumsum
0             25.23         11            0.106796   0.106796
1              5.34         10            0.097087   0.203883
2             27.77         10            0.097087   0.300971
3             17.71         10            0.097087   0.398058
4             19.85         10            0.097087   0.495146
...             ...        ...                 ...        ...
2847          21.61          1            0.009709  97.048544
2848           1.26          1            0.009709  97.058252
2849           5.40          1            0.009709  97.067961
2850          14.76          1            0.009709  97.077670
2851          17.64          1            0.009709  97.087379

[2852 rows x 4 columns]

In [22]:
result = Univariate.FreqTable("Crop_Yield_MT_per_HA",df)
result

     Unique_values  Frequency  Relative_Frequency     Cumsum
0            1.530         44            0.427184   0.427184
1            2.160         39            0.378641   0.805825
2            1.800         37            0.359223   1.165049
3            2.520         36            0.349515   1.514563
4            0.900         36            0.349515   1.864078
..             ...        ...                 ...        ...
845          4.170          1            0.009709  97.048544
846          4.520          1            0.009709  97.058252
847          4.090          1            0.009709  97.067961
848          3.645          1            0.009709  97.077670
849          4.194          1            0.009709  97.087379

[850 rows x 4 columns]

In [23]:
result = Univariate.FreqTable("Extreme_Weather_Events",df)
result

    Unique_values  Frequency  Relative_Frequency     Cumsum
0               1        957            9.291262   9.291262
1               6        929            9.019417  18.310680
2               9        917            8.902913  27.213592
3               3        915            8.883495  36.097087
4               5        914            8.873786  44.970874
5              10        908            8.815534  53.786408
6               2        899            8.728155  62.514563
7               0        899            8.728155  71.242718
8               4        895            8.689320  79.932039
9               7        884            8.582524  88.514563
10              8        883            8.572816  97.087379

In [24]:
result = Univariate.FreqTable("Irrigation_Access_%",df)
result

      Unique_values  Frequency  Relative_Frequency     Cumsum
0             79.29          7            0.067961   0.067961
1             74.86          6            0.058252   0.126214
2             19.24          6            0.058252   0.184466
3             98.54          6            0.058252   0.242718
4             80.44          6            0.058252   0.300971
...             ...        ...                 ...        ...
5998          55.04          1            0.009709  97.048544
5999          45.20          1            0.009709  97.058252
6000          49.31          1            0.009709  97.067961
6001          22.32          1            0.009709  97.077670
6002          78.53          1            0.009709  97.087379

[6003 rows x 4 columns]

In [25]:
result = Univariate.FreqTable("Pesticide_Use_KG_per_HA",df)
result

      Unique_values  Frequency  Relative_Frequency     Cumsum
0             37.76          8            0.077670   0.077670
1             44.69          8            0.077670   0.155340
2              0.72          8            0.077670   0.233010
3              2.78          8            0.077670   0.310680
4              5.82          8            0.077670   0.388350
...             ...        ...                 ...        ...
4338          40.52          1            0.009709  97.048544
4339           4.81          1            0.009709  97.058252
4340          33.34          1            0.009709  97.067961
4341          40.88          1            0.009709  97.077670
4342          44.54          1            0.009709  97.087379

[4343 rows x 4 columns]

In [26]:
result = Univariate.FreqTable("Fertilizer_Use_KG_per_HA",df)
result

      Unique_values  Frequency  Relative_Frequency     Cumsum
0              6.07          6            0.058252   0.058252
1             77.99          6            0.058252   0.116505
2             93.14          6            0.058252   0.174757
3             65.33          6            0.058252   0.233010
4             72.31          6            0.058252   0.291262
...             ...        ...                 ...        ...
6309          37.10          1            0.009709  97.048544
6310          97.89          1            0.009709  97.058252
6311          64.48          1            0.009709  97.067961
6312          68.91          1            0.009709  97.077670
6313          10.95          1            0.009709  97.087379

[6314 rows x 4 columns]

In [27]:
result = Univariate.FreqTable("Soil_Health_Index",df)
result

      Unique_values  Frequency  Relative_Frequency     Cumsum
0             79.38          8            0.077670   0.077670
1             63.03          7            0.067961   0.145631
2             64.29          6            0.058252   0.203883
3             63.62          6            0.058252   0.262136
4             31.44          6            0.058252   0.320388
...             ...        ...                 ...        ...
5313          30.34          1            0.009709  97.048544
5314          97.90          1            0.009709  97.058252
5315          36.80          1            0.009709  97.067961
5316          65.53          1            0.009709  97.077670
5317          59.38          1            0.009709  97.087379

[5318 rows x 4 columns]

In [28]:
result = Univariate.FreqTable("Economic_Impact_Million_USD",df)
result

      Unique_values  Frequency  Relative_Frequency     Cumsum
0            616.60          4            0.038835   0.038835
1           1012.69          3            0.029126   0.067961
2            447.71          3            0.029126   0.097087
3            227.76          3            0.029126   0.126214
4            643.72          3            0.029126   0.155340
...             ...        ...                 ...        ...
9626         447.74          1            0.009709  97.048544
9627         180.21          1            0.009709  97.058252
9628         649.78          1            0.009709  97.067961
9629         482.38          1            0.009709  97.077670
9630         453.14          1            0.009709  97.087379

[9631 rows x 4 columns]

In [46]:
from UnivariateAnalysis import Univariate
import numpy as np
lesser, greater = Univariate.Find_outlier(df,Quan)

KeyError: 'Min'