In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
dataset=dataset.drop("User ID",axis=1)

In [5]:
dataset.isnull().sum()

Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [6]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.astype(int)

In [7]:
dataset.head()

   Age  EstimatedSalary  Purchased  Gender_Male
0   19            19000          0            1
1   35            20000          0            1
2   26            43000          0            0
3   27            57000          0            0
4   19            76000          0            1

In [8]:
indep=dataset[["Age","EstimatedSalary","Gender_Male"]]
dep=dataset[["Purchased"]]

In [9]:
indep.head()

   Age  EstimatedSalary  Gender_Male
0   19            19000            1
1   35            20000            1
2   26            43000            0
3   27            57000            0
4   19            76000            1

In [10]:
dep.head()

   Purchased
0          0
1          0
2          0
3          0
4          0

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=0.3,random_state=0)

In [12]:
x_train,x_test,y_train,y_test

(     Age  EstimatedSalary  Gender_Male
 92    26            15000            1
 223   60           102000            1
 234   38           112000            0
 232   40           107000            1
 377   42            53000            0
 ..   ...              ...          ...
 323   48            30000            0
 192   29            43000            1
 117   36            52000            1
 47    27            54000            0
 172   26           118000            0

 [280 rows x 3 columns],
      Age  EstimatedSalary  Gender_Male
 132   30            87000            1
 309   38            50000            0
 341   35            75000            1
 196   30            79000            0
 246   35            50000            0
 ..   ...              ...          ...
 216   49            65000            1
 259   45           131000            0
 49    31            89000            0
 238   46            82000            0
 343   47            51000            0

 [120 rows x 3 columns],
      Purchased
 92           0
 223          1
 234          0
 232          1
 377          0
 ..         ...
 323          1
 192          0
 117          0
 47           0
 172          0

 [280 rows x 1 columns],
      Purchased
 132          0
 309          0
 341          0
 196          0
 246          0
 ..         ...
 216          0
 259          1
 49           0
 238          0
 343          1

 [120 rows x 1 columns])

In [ ]:
# 1. GaussianNB Naive bayes

In [13]:
from sklearn.naive_bayes import GaussianNB

In [14]:
classifier = GaussianNB()

In [15]:
classifier.fit(x_train,y_train)

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GaussianNB()

In [16]:
y_pred=classifier.predict(x_test)

In [17]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [18]:
print(cm)

[[74  5]
 [ 8 33]]

In [19]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

In [20]:
print(clf_report)   # classification report for GaussianNB

              precision    recall  f1-score   support

           0       0.90      0.94      0.92        79
           1       0.87      0.80      0.84        41

    accuracy                           0.89       120
   macro avg       0.89      0.87      0.88       120
weighted avg       0.89      0.89      0.89       120

In [21]:
# 2.Multinomial Naive bayes

In [25]:
from sklearn.naive_bayes import MultinomialNB
classifier =MultinomialNB()
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print(cm)

[[68 11]
 [28 13]]

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [26]:
print(clf_report)   # classification report for  MultinomialNB

              precision    recall  f1-score   support

           0       0.71      0.86      0.78        79
           1       0.54      0.32      0.40        41

    accuracy                           0.68       120
   macro avg       0.62      0.59      0.59       120
weighted avg       0.65      0.68      0.65       120

In [ ]:
# 3.BernoulliNB Naive bayes

In [27]:
from sklearn.naive_bayes import BernoulliNB
classifier =BernoulliNB()
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print(cm)

[[79  0]
 [41  0]]

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\USER\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\USER\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\USER\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [28]:
print(clf_report) # classification report for BernoulliNB

              precision    recall  f1-score   support

           0       0.66      1.00      0.79        79
           1       0.00      0.00      0.00        41

    accuracy                           0.66       120
   macro avg       0.33      0.50      0.40       120
weighted avg       0.43      0.66      0.52       120

In [ ]:
#4.CategoricalNB

In [29]:
from sklearn.naive_bayes import CategoricalNB
classifier =CategoricalNB()
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print(cm)

[[76  3]
 [ 9 32]]

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [30]:
print(clf_report) # classification report for CategoricalNB

              precision    recall  f1-score   support

           0       0.89      0.96      0.93        79
           1       0.91      0.78      0.84        41

    accuracy                           0.90       120
   macro avg       0.90      0.87      0.88       120
weighted avg       0.90      0.90      0.90       120

In [ ]:
#5.ComplementNB

In [31]:
from sklearn.naive_bayes import ComplementNB
classifier=ComplementNB()
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print(cm)

[[42 37]
 [20 21]]

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [32]:
print(clf_report) # classification report for ComplementNB

              precision    recall  f1-score   support

           0       0.68      0.53      0.60        79
           1       0.36      0.51      0.42        41

    accuracy                           0.53       120
   macro avg       0.52      0.52      0.51       120
weighted avg       0.57      0.52      0.54       120