In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [4]:
dataset.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [5]:
dataset.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [6]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [7]:
dataset=dataset.astype(int)

In [8]:
dataset.head()

    User ID  Age  EstimatedSalary  Purchased  Gender_Male
0  15624510   19            19000          0            1
1  15810944   35            20000          0            1
2  15668575   26            43000          0            0
3  15603246   27            57000          0            0
4  15804002   19            76000          0            1

In [10]:
dataset=dataset.drop("User ID",axis=1)

In [11]:
dataset.head()

   Age  EstimatedSalary  Purchased  Gender_Male
0   19            19000          0            1
1   35            20000          0            1
2   26            43000          0            0
3   27            57000          0            0
4   19            76000          0            1

In [12]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [13]:
indep=dataset[["Age","EstimatedSalary","Gender_Male"]]
dep=dataset[["Purchased"]]

In [14]:
indep.head()

   Age  EstimatedSalary  Gender_Male
0   19            19000            1
1   35            20000            1
2   26            43000            0
3   27            57000            0
4   19            76000            1

In [15]:
dep.head()

   Purchased
0          0
1          0
2          0
3          0
4          0

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)

In [17]:
x_train,x_test,y_train,y_test

(     Age  EstimatedSalary  Gender_Male
 218   46            96000            0
 101   28            59000            1
 311   39            96000            1
 194   28            89000            1
 326   41            72000            1
 ..   ...              ...          ...
 323   48            30000            0
 192   29            43000            1
 117   36            52000            1
 47    27            54000            0
 172   26           118000            0

 [266 rows x 3 columns],
      Age  EstimatedSalary  Gender_Male
 132   30            87000            1
 309   38            50000            0
 341   35            75000            1
 196   30            79000            0
 246   35            50000            0
 ..   ...              ...          ...
 168   29           148000            1
 150   26            15000            0
 393   60            42000            1
 66    24            19000            1
 240   42           149000            1

 [134 rows x 3 columns],
      Purchased
 218          0
 101          0
 311          1
 194          0
 326          0
 ..         ...
 323          1
 192          0
 117          0
 47           0
 172          0

 [266 rows x 1 columns],
      Purchased
 132          0
 309          0
 341          0
 196          0
 246          0
 ..         ...
 168          1
 150          0
 393          1
 66           0
 240          1

 [134 rows x 1 columns])

In [18]:
from sklearn.linear_model import LogisticRegression
classifier= LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(random_state=0)

In [20]:
y_pred=classifier.predict(x_test)

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [22]:
print(cm)

[[85  0]
 [49  0]]

In [23]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\USER\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\USER\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [24]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.63      1.00      0.78        85
           1       0.00      0.00      0.00        49

    accuracy                           0.63       134
   macro avg       0.32      0.50      0.39       134
weighted avg       0.40      0.63      0.49       134

In [25]:
classifier.predict([[40,300,1,]])

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])