In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('Social_Network_Ads.csv')

In [3]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset=dataset.astype(int)

In [7]:
dataset.head()

    User ID  Age  EstimatedSalary  Purchased  Gender_Male
0  15624510   19            19000          0            1
1  15810944   35            20000          0            1
2  15668575   26            43000          0            0
3  15603246   27            57000          0            0
4  15804002   19            76000          0            1

In [8]:
indep=dataset[['Age', 'EstimatedSalary','Gender_Male']]
dep=dataset['Purchased']

In [9]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
from sklearn.svm import SVC

In [12]:
#https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter

In [13]:
from sklearn.model_selection import GridSearchCV

param_grid = {'kernel':['linear','rbf','poly','sigmoid'],
             'gamma':['auto','scale'],
             'C':[10,100,1000,2000,3000]} 



grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

GridSearchCV(estimator=SVC(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']},
             scoring='f1_weighted', verbose=3)

In [15]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [16]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}: 0.9100355779243318

In [17]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[80  5]
 [ 7 42]]

In [18]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.92      0.94      0.93        85
           1       0.89      0.86      0.88        49

    accuracy                           0.91       134
   macro avg       0.91      0.90      0.90       134
weighted avg       0.91      0.91      0.91       134

In [20]:
#from sklearn.metrics import roc_auc_score

#roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

In [21]:
table=pd.DataFrame.from_dict(re)

In [22]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006739,0.005129,0.005138,0.004338,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
1,0.008320,0.005269,0.002713,0.002308,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.867478,0.886792,0.869709,0.944161,0.943041,0.902236,0.034431,3
2,0.003281,0.001594,0.003466,0.001888,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.799620,0.808392,0.787943,0.924528,0.901744,0.844445,0.056918,11
3,0.001921,0.001375,0.004427,0.004167,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.762677,0.738916,0.655795,0.796284,0.766556,0.744045,0.047743,39
4,0.006074,0.001309,0.004075,0.001626,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
5,0.003005,0.001345,0.005809,0.001519,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.867478,0.886792,0.869709,0.944161,0.943041,0.902236,0.034431,3
6,0.005441,0.002306,0.002635,0.002422,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.799620,0.808392,0.787943,0.924528,0.901744,0.844445,0.056918,11
7,0.002195,0.001029,0.004242,0.003091,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.762677,0.738916,0.753180,0.778067,0.766556,0.759879,0.013172,31
8,0.015996,0.002212,0.002193,0.001947,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
9,0.008858,0.003234,0.006514,0.003288,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.867478,0.886792,0.870362,0.944161,0.943041,0.902367,0.034308,1
10,0.021165,0.003432,0.003898,0.003541,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.822092,0.787284,0.766556,0.924528,0.901744,0.840441,0.062370,13
11,0.004586,0.004895,0.003852,0.003884,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.808927,0.714931,0.633719,0.718497,0.766556,0.728526,0.058625,40
12,0.011116,0.004298,0.003328,0.004151,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
13,0.001668,0.002380,0.008186,0.002444,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.867478,0.886792,0.870362,0.944161,0.943041,0.902367,0.034308,1
14,0.020806,0.012337,0.005097,0.004337,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.822092,0.787284,0.766556,0.924528,0.901744,0.840441,0.062370,13
15,0.001004,0.002009,0.006092,0.005018,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.808927,0.714931,0.698113,0.796284,0.766556,0.756962,0.043745,32
16,0.090286,0.018063,0.005100,0.004564,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
17,0.006732,0.005271,0.006891,0.004422,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.826263,0.866968,0.851527,0.925272,0.923510,0.878708,0.039503,6
18,0.160696,0.030099,0.007928,0.015856,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
19,0.002398,0.003642,0.000196,0.000392,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.791752,0.714931,0.698113,0.796284,0.766556,0.753527,0.040048,36
20,0.101557,0.019021,0.003635,0.003451,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
21,0.005150,0.004041,0.006046,0.004948,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.847141,0.866968,0.851527,0.925272,0.923510,0.882884,0.034529,5
22,0.212970,0.124201,0.007547,0.003791,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
23,0.000501,0.000634,0.001811,0.003621,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.808927,0.714931,0.698113,0.796284,0.766556,0.756962,0.043745,32
24,0.242626,0.146369,0.005277,0.005624,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
25,0.012481,0.003867,0.006673,0.005068,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.826263,0.866968,0.851527,0.886792,0.903610,0.867032,0.026948,7
26,0.367216,0.102168,0.004606,0.007419,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
27,0.003504,0.004159,0.001010,0.001569,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.791752,0.714931,0.698113,0.796284,0.766556,0.753527,0.040048,36
28,0.233711,0.136462,0.002009,0.004018,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
29,0.014572,0.005456,0.007942,0.003976,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.826263,0.866968,0.851527,0.886792,0.903610,0.867032,0.026948,7
30,0.379373,0.125180,0.003022,0.003893,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
31,0.001538,0.002604,0.008688,0.002072,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",0.808927,0.714931,0.698113,0.796284,0.766556,0.756962,0.043745,32
32,0.356632,0.188777,0.003085,0.003829,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
33,0.043431,0.017455,0.009076,0.006786,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.826263,0.866968,0.851527,0.847020,0.883278,0.855011,0.019206,9
34,1.101809,0.237537,0.007431,0.001718,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
35,0.001275,0.001734,0.004292,0.004862,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.791752,0.714931,0.698113,0.796284,0.766556,0.753527,0.040048,36
36,0.590672,0.111688,0.008348,0.001976,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
37,0.053869,0.011051,0.014993,0.008818,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.826263,0.866968,0.851527,0.847020,0.883278,0.855011,0.019206,9
38,1.273976,0.390032,0.007047,0.001739,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
39,0.007332,0.004511,0.007665,0.002641,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",0.808927,0.714931,0.698113,0.796284,0.766556,0.756962,0.043745,32

In [24]:
age=float(input("Age:"))
Estimated_salary=float(input("Estimated_salary:"))
sex_male=int(input("Sex Male 0 or 1:"))

Age: 43
Estimated_salary: 70000
Sex Male 0 or 1: 1

In [25]:
Future_Prediction=grid.predict([[age,Estimated_salary,sex_male]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]