In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import matplotlib.pyplot as plt

In [5]:
dataset= pd.read_csv("insurance_pre.csv")

In [6]:
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [7]:
dataset.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
charges     0
dtype: int64

In [8]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [9]:
dataset=dataset.astype(int)

In [10]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [11]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [12]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [13]:
indep

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [14]:
dep=dataset[['charges']]

In [15]:
dep

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [16]:
from sklearn.ensemble import RandomForestRegressor

In [18]:
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['friedman_mse','squared_error','absolute_error','poisson'],'max_features': ['auto','sqrt','log2'],'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(),param_grid, refit = True, verbose= 3,n_jobs=-1)
grid.fit(indep,dep)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
12 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
28 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\USER\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\USER\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.81631576 0.82736225 0.81594564 0.82607723
        nan        nan 0.80840006 0.82887415 0.80751838 0.82803524
        nan        nan 0.81552903 0.82976928 0.81585388 0.8309155
        nan        nan 0.81354215 0.82944867 0.8118653  0.83068218]
  warnings.warn(
C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['friedman_mse', 'squared_error',
                                       'absolute_error', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [19]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100}:

In [20]:
table=pd.DataFrame.from_dict(re)

In [21]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003339,0.002455,0.000000,0.000000,friedman_mse,auto,10,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.001755,0.000956,0.000000,0.000000,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.108296,0.012497,0.010402,0.003577,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.836006,0.761108,0.851827,0.810904,0.821734,0.816316,0.030839,9
3,0.867369,0.049111,0.032651,0.001533,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.856304,0.772213,0.851500,0.822472,0.834322,0.827362,0.030113,7
4,0.098504,0.008306,0.009405,0.002916,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.834727,0.775264,0.829355,0.817098,0.823284,0.815946,0.021179,10
5,0.836282,0.073484,0.046031,0.024382,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.854177,0.771321,0.847244,0.820053,0.837590,0.826077,0.029681,8
6,0.000435,0.000871,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.001073,0.000662,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.099097,0.040580,0.009843,0.008390,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.847535,0.737740,0.841086,0.811455,0.804185,0.808400,0.039038,15
9,1.647564,0.063657,0.080832,0.012848,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.856911,0.773745,0.854567,0.820924,0.838224,0.828874,0.030450,5
10,0.230519,0.037330,0.017255,0.002612,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.839557,0.743700,0.840157,0.802423,0.811755,0.807518,0.035238,16
11,1.537048,0.085691,0.052389,0.006008,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.852433,0.771710,0.855531,0.825808,0.834694,0.828035,0.030243,6
12,0.000000,0.000000,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.006255,0.007660,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.457092,0.038334,0.012715,0.006371,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.847995,0.751002,0.836911,0.814811,0.826927,0.815529,0.034075,12
15,4.281420,0.143350,0.056076,0.012000,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.853916,0.775809,0.853322,0.827170,0.838630,0.829769,0.028757,3
16,0.457961,0.021969,0.022502,0.009403,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.827820,0.752619,0.840483,0.820551,0.837797,0.815854,0.032410,11
17,4.665198,0.183224,0.063972,0.010108,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.856099,0.773905,0.858829,0.823606,0.842138,0.830915,0.031123,1
18,0.001730,0.001426,0.000000,0.000000,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.002843,0.003000,0.000000,0.000000,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.221794,0.028598,0.010283,0.004115,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.840780,0.762620,0.829363,0.801651,0.833297,0.813542,0.028695,13
21,1.757854,0.053136,0.066463,0.016398,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.856986,0.775586,0.851985,0.820474,0.842213,0.829449,0.029701,4
22,0.198217,0.031789,0.006564,0.007679,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.838768,0.746345,0.843033,0.806703,0.824477,0.811865,0.035139,14
23,1.779080,0.294411,0.045651,0.012050,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.857178,0.777827,0.858594,0.824547,0.835265,0.830682,0.029439,2

In [22]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:40
BMI:51
Children:3
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [23]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[9880.95]

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(